name: Minigame_Score
version: ${project.version}
main: red.man10.minigame_score.Minigame_Score
commands:
  mgscore:
    description: Command no setsumei
    usage: /<command>
    default: true
permissions:
  minigamescore:
    default: OP
